server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: ""
        default-application-name: application
  autoconfigure:
    exclude: org.springframework.cloud.config.server.config.DefaultRepositoryConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info
